# Generated by Django 6.0.2 on 2026-03-06 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnosis', '0002_scan'),
    ]

    operations = [
        migrations.AddField(
            model_name='diagnosis',
            name='recommendation',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scan',
            name='recommendation',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
